development:
  secret_key_base: o1V03nCLdygp7tB1gxbDfQXGfSKMBOP12bpY7FHZuyBsJ8egUpygsHXLUDMO2LKb8afbMxjExBdaqimugPJaRHLru9w2bZTyRypRIqizesfRvinuDtqkHgpcNAzTgnk4QDBu48ApCMmMCzreP0gCd8aBAfVngg6k18i7IYWfHNh1TsKqPjpKfnFD2HFe3x7BpGbcqLXotmSKjjscT3bAYBFGKlrBQy25656CxTI4urgu4nJFCs7odpxp9LAtl7GL
